### ISSUE TITLE
Add Adetailer support

### ISSUE THREAD

**Issue by ahsanba-id** [Stability-AI/StableSwarmUI#106]
I'm always amazed by a1111 UI for its Hi-res fix and Adetailer. Restore faces isn't too good, as it can change the structure of the model's face, which many AI art artists prefer to avoid. However, this is not the case if Hi-res fix combined with Adetailer, especially using media pipe face full. I see yours has similarities to Hi-res fix. Integrating Adetailer into your program would be nice. :)

**Comment by arafatx** [comment]
I like StableSwarmUI because it can use ComfyUI as its backend. I would be happy to switch from A1111 completely if those extensions could be ported.

**Comment by mcmonkey4eva** [comment]
Hires fix: that's called the refiner stage in swarm, just configure it like:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/4e6b3510-b0dd-46d8-a884-0f2d93a07555)
if you use `PostApply` and don't enable the model option, behavior is effectively identical to auto webui's hires fix.

-----------

'Adetailer': haven't copied the exact extension, but I realized I could take the concept and implement it an entire step further: https://github.com/Stability-AI/StableSwarmUI/discussions/11#discussioncomment-7236821 this new feature behaves fairly similar to "ADetailer", except it lets you define the segmentation region to be anything (rather than just the face) and lets you do multiple regions.

If there's any secondary features of the relevant original extension you find are missing, or any improvements you think could be made, please let me know!

**Comment by misterteetee** [comment]
Is there anything else required to test this out? I've updated stableswarm and comfyui. Used your example configuration and the output fails. 

```
07:12:51.553 [Debug] ComfyUI stdout: Requested to load SDXLClipModel
07:12:51.554 [Debug] ComfyUI stdout: Loading 1 new model
07:12:57.378 [Debug] ComfyUI stdout: ERROR:root:!!! Exception during processing !!!
07:12:57.378 [Debug] ComfyUI stdout: ERROR:root:Traceback (most recent call last):
07:12:57.379 [Debug] ComfyUI stdout:   File "C:\Users\nobody\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
07:12:57.380 [Debug] ComfyUI stdout:     output_data, output_ui = get_output_data(obj, input_data_all)
07:12:57.381 [Debug] ComfyUI stdout:   File "C:\Users\nobody\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
07:12:57.381 [Debug] ComfyUI stdout:     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
07:12:57.382 [Debug] ComfyUI stdout:   File "C:\Users\nobody\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
07:12:57.383 [Debug] ComfyUI stdout:     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
07:12:57.384 [Debug] ComfyUI stdout:   File "C:\Users\nobody\StableSwarmUI\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmImages.py", line 26, in scale
07:12:57.384 [Debug] ComfyUI stdout:     scale = math.sqrt(mpTarget / (oldWidth * oldHeight))
07:12:57.385 [Debug] ComfyUI stdout: ZeroDivisionError: division by zero
07:12:57.386 [Debug] ComfyUI stdout:
07:12:57.387 [Debug] ComfyUI stdout: Prompt executed in 16.87 seconds
07:12:57.547 [Info] No images were generated (all refused, or failed).
```

**Comment by mcmonkey4eva** [comment]
Try with the new update ^ should hopefully fix edge cases when masks are detected wrong?
If it happens again, please post the prompt you're trying

**Comment by koloved** [comment]
It's a pity that it's not even close to the Adetailer available in A1111, which allows you to use several models simultaneously to improve individual parts of an image. @mcmonkey4eva
