### ISSUE TITLE
Wildcard not showing

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#177]
wildcards I created in SwarmUI and copied to Data/Wildcards are not showing.
New wildcards do create new files, but nothing is shown as the screenshot:

<img width="1542" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/a7cb498b-2239-42dc-a54c-9a3d3ff81ebd">

**Comment by beltonk** [comment]
For copied wildcards, only the folder tree is shown, nothing on the right:

<img width="1135" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/5ffd39c6-8e00-457c-8ce3-a7048722a736">

**Comment by mcmonkey4eva** [comment]
That appears to be a JS error (there's an entire block just not generated in). Does CTRL+F5 (hard refresh) fix it? If not, can you open browser console (CTRL+Shift+i) and see if there's an error message?

**Comment by beltonk** [comment]
hard refresh no difference. browser console has no error too. Just the Wildcard tab is not working.

**Comment by mcmonkey4eva** [comment]
That's... very strange. the entire content container is missing, including the header line:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/c880b095-f1aa-4ed5-9a68-76e0b40d5e59)

So I'd expect a basic loading error, which should show in JS console

**Comment by beltonk** [comment]
The component structure is all the same across all other tabs. The only difference is the "Create New Wildcard" button.
I trace down the codes, all javascript works fine for Wildcards, fullcontent is loaded, just not showing, which navigating the folder tree.

One thing very interesting is when I "inspect" -> remove the "Create New Wildcard" button ("wildcards_list_create_new_button" button) from the browser_container div, then the fullcontent pane is showing correctly.

<img width="775" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/33edf3bc-b671-4f29-b362-bf5159fde532">

Next I moved the "Create New Wildcard" button to the "wildcardsbrowser-foldertree" div, then it also shows correctly like this:

<img width="775" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/fb218d6b-8a93-4e2d-a7ec-6bd428045101">

Perhaps this is some HTML / div / button issue? I'm not a front-end developer, but this works for me.

**Comment by mcmonkey4eva** [comment]
Ah, I replicated it after that screenshot - it doesn't happen in Firefox, it only happens in Chromium-based browsers.

There's a row of divs are that were (for my window size), 240 | 7 | 945 px. It was this width for the Presets tab, and for the wildcards tab.
The presets tab has buttons over top, the wildcards does too in the same way.

For reasons beyond sane understanding, chrome decided that the 945 block was too wide on the wildcards tab, but not the presets tab. This  was, in fact, controlled by the buttons that were vertically above the block and thus had nothing to do with its horizontal alignment.

It's now fixed by way of telling chrome it's not allowed to attempt content wrapping there.

**Comment by beltonk** [comment]
It is working now after the fix.

<img width="1006" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/39476894/27a4adf7-3e74-400f-99c4-644e1a170c14">

But don't you think it would look better without the row gap caused by the button alone?

![image](https://github.com/Stability-AI/StableSwarmUI/assets/39476894/028668ae-253d-494a-b672-3d44c54cd0f1)
