### ISSUE TITLE
Suggested UI Layout & Groupings

### ISSUE THREAD

**Issue by beltonk** [Stability-AI/StableSwarmUI#178]
IMO, current grouping and orders, do not really reflect the rough node sequence. Our eyes need to jump around different places and check carefully before generation, plus those expand/collapse & auto-enable design. Users may be lost or accidentally enable something without params that prevent from proper generation. And the parameters do not seem to be grouped exactly by their functional capabilities, look like kind of mix for now.

For me, it would be more intuitive to setup parameters in logical sequence & groupings, for example:

1. Diffusion Models
Base Model: sd_xl_base_1.0.safetensors
VAE: sdxl_vae.safetensors
Refiner Model:  Off

2. Text Prompts (postitive / negative prompts be together on the left pane or under the output image)
Presets / Styles: ...
Positive Prompt: xxx
Negative Prompt: yyy

3. Generation Parameters
Core Parameters: Images, Seed, Steps, CFG Scale
Variation Seed: Variation Seed, Strength
Resolution: 1:1 (1024x1024)
Sampler: dpmpp_2m_sde_gpu
Scheduler: Karras
Clip Skip: -1
Init Image: Off
ControlNet: Image Input, Preprocessor, Model, Strength, ControlNet Start, ControlNet End

4. Advanced (collapsed by default)

At least for ordering, it is not easy to re-order by messing around the Ordering Priority values without a GUI drag-and-drop ordering. I did try, but I am not able to customize the orders like above, e.g. cannot place Model & VAE on the top.

Image can be dragged to a text prompt is also something not usual and not intuitive. Firstly, users need to understand what ReVision / IP Adapter is for, aware of this UI interaction (drag-and-drop to add image and unhide ReVision section), and know how to tweak ReVision / IP Adapter settings, assuming they already know they are actually separate things. Not to mention multiple images can be added for now. Why not simply create an image box, group related tunings together, and separate capabilities by groups?

**Comment by beltonk** [comment]
I understand how you design & organize things at the first place.
Just I think there may be room to improve user-friendliness by balancing "technical", "functional" and "logical" ordering and groupings, which is not easy and subjective.

Bottom panes are my favourite design, making things so much easier to access, enable/disable by simply one-click toggling, instead of messing up the prompts.

**Comment by mcmonkey4eva** [comment]
`(postitive / negative prompts be together on the left pane or under the output image)`
I consider the negative prompt to be a fiddly parameter that is rarely useful in practice to actively mess with, particular on SDXL (on SDv1 it was a bit more useful), so it lives with the other parameters. Prompt is the key focus for generation, so it's front-n-center. If you really want them together, you can go to User -> Parameter Configuration and check "Visible Normally" next to Prompt to have it appear on the left as a parameter.

`Base Model: sd_xl_base_1.0.safetensors` this is the other coremost feature and deserves a unique UI placement (the whole selection menu). A standard dropdown input becomes rapidly useless once you start having lots of models.

`VAE: sdxl_vae.safetensors` this is a suuuuuper obscure setting, that you should rarely have to touch if things are going well - 90% of the time the correct VAE should just be in the model. Earlier today however I did add a UserSetting to configure your default SDXL + SDv1 VAE overrides (eg if you want to use the fp16-fix VAE with SDXL, you can do that, or enable NAI for your SDv1 models if you're an anime fan) (either way it's a set-once-and-forget for the most part) (but also it does get the fancy UI slot at the bottom just cause I have all models listed that way)

`Refiner Model: Off` imo it'd be really weird for this to not be grouped with the other refiner settings.

`Firstly, users need to understand what ReVision / IP Adapter is for,` this is an unfortunate consequence of there being 3+ different options for image-prompting - in the first version of that UI, it was _just_ ReVision and it was _just_ drag image in and you're good. the IPAdapter support made the configuration less intuitive, and needs a bit of a rework (mostly just automating away the install/download parts) (but also I have broader plans to revamp the image input setup, I believe I mentioned in another thread recently re controlnet)

`aware of this UI interaction (drag-and-drop to add image and unhide ReVision section),` we went over this before https://github.com/Stability-AI/StableSwarmUI/issues/158 it's explicitly stated on-page and you definitely don't need to "unhide the ReVision section".

`Generation Parameters` that section is more or less the order that's there - or close enough.
(barring ClipSkip, which is an advanced parameter for SDv1 that is no longer relevant as of SDXL. And the sampler/scheduler being a lil wonky because of the comfy backend thing but that's got a planned fix coming)

**Comment by beltonk** [comment]
I just mean the UI is now a bit scattered for now. Need to look around different spots and understand the hidden / automatic behaviours...

I totally agree with you some features are rare to use. Let's focus on the ordering flexibility. I'm not able to order model, VAE to the top, for example, and not even close to my desired ordering mentioned in the first post... and even I make model & positive prompt visible, they are still duplicated on the UI...

I know you have explained how it works for ReVision, it is just not intuitive... and the same feature is not centralized at one place. At least, someone stupid like me, not being aware of the tips in the positive text prompt, would look around like init image, trying ControlNet input image, drag-and-drop to the output image pane, or enable that image prompt in advanced settings. And I didn't know what ReVision is, possibly those users from A1111.

I understand ClipSkip is for SD 1.5 too, just for some use cases we still need 1.5...
