### ISSUE TITLE
Custom Images filename and output directory

### ISSUE THREAD

**Issue by Katmoget** [Stability-AI/StableSwarmUI#19]
Hi

I have a few questions regarding custom settings for filename and directory 
- when I set the server OutputPath to for ex D:\SD\Images and the user OutputPath (in the user tab) to [year]-[month]-[day]/[seed]-[model]-[prompt]  , a "local" folder is created automatically and the images are saved in D:\SD\Images\local\2023-08-03 instead of  D:\SD\Images\2023-08-03
how can I stop the "Local" folder from being generated and save directly in the D:\SD\Images\2023-08-03 folder ?

- for a single user, do I need to set the  OutputPath and file save settings in the user tab and in the server settings, I don't seem to be able to set the server setting for all users, If I don't add settings in the user tab the files are not saved.

- Would it be possible, as in WebUI1111. to use [number] in the custom file name to add a sequential number to the file, for ex : [number]-[seed]-[model]-[prompt] instead of having a -1, -2 etc at the end as it is currently the case in StableSwarmUI

Thanks

**Comment by mcmonkey4eva** [comment]
- I added a new setting: `AppendUserNameToOutputPath`, you can turn that off to remove that
- you want to use user settings for those, the server "default user" settings are defaults (for multi-user setups)
- added, as written, `[number]` in the format will be replaced with the deduplication number ID if you want to reposition it.
Note that if you're just trying to order the images naturally, i'd recommend a sort by date/time rather than name, or include that into the filename

**Comment by Katmoget** [comment]
excellent, thank you!
