### ISSUE TITLE
Docker woes, and some workarounds in lieu of PR

### ISSUE THREAD

**Issue by krahnikblis** [Stability-AI/StableSwarmUI#193]
hi, i really wanna believe in the swarm! and docker, because sheesh i don't want everyone's FOSS all over my main system. so, i'm on my only Windows box, which has WSL and Docker Desktop, and i hacked the container into life (but it took many frustrating hours - how was i to know that Git automatically adds carriage returns to shell scripts??? given i'm a Git noob, i'm not messing with how to use version control and PRs and all, sorry not sorry)

anyway, here are things that i did to get it to work, maybe these can help someone else, or be added to the main package:
1. **BEFORE** `git clone` this repo, i needed to run `git config --global core.autocrlf false`. this was because in my case, all the .sh files in the Docker image were altered by Git clone process, and the whole setup got messed up and the server wouldn't run
2. the `launch-docker.sh` of course assumes you're running in a Linux env, so i simply copied the contents and ran them in Powershell (maybe include a .bat file for Windows Docker users?)
3. adding ComfyUI Manager failed because it needed CV2, which gets installed by [`src/BuiltinExtensions/ComfyUIBackend/ComfyUISelfStartBackend.cs` at line 190](https://github.com/Stability-AI/StableSwarmUI/blob/master/src/BuiltinExtensions/ComfyUIBackend/ComfyUISelfStartBackend.cs#L190) which itself was missing some dependency. i tried a lot of things and learned a lot about Docker along the way, ultimately per some chitchat [here](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo), i learned about "installing `opencv-python-headless` python dependency instead of `opencv-python`. That includes a precompiled binary wheel with no external dependencies (other than numpy), and is **intended for headless environments like Docker**. This saved almost 700mb in my docker image compared with using the `python3-opencv` Debian package (with all its dependencies)." - i did this the hard way (editing the file from inside the container), but perhaps this could be worked into a future release. it worked and now manager shows up in the UI
change this: `await install("opencv_python", "opencv-python");`
to this: `await install("opencv_python", "opencv-python-headless");`
4. i think i did something along the way while wrenching all this, don't know how to undo - there are 2 instances of comfy UI self start backends. every time i delete the 2nd one, when restarting the server it shows up again. i'm sure this is a waste of resources, and probably just a digit in a yaml somewhere, but i can't find it... 
5. WSL Fs up all the mounts, i don't know what to do. it's really hard to get to them, but i found [this article](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly) which looks like a whole saturday so i'll get to it after a trip to Jamaica this week lawdamercy... 

just for you-know-whats and giggles i saved my adjustments from the container back to the image so i don't need to repeat things later maybe - `docker commit container_name stableswarmui` (i don't know if this saves my lost volumes and mounts into the image?)

**Comment by mcmonkey4eva** [comment]
` i don't want everyone's FOSS all over my main system` lol. Understandable.
For the record, Swarm stays 99% confined to its own folder, the exceptions are (1) dependencies like dotnet/git naturally have global installs, and (2) sometimes the backend comfy's python dependencies cache things in silly places like user dir. They're generally not supposed to be doing that (thanks to the python embedded version used) so idk how often it does in practice.
ie: if the concern is simple cleanliness you're basically fine just not using docker for Swarm. If it's security paranoia or whatever, yeah docker is understandable. Should probably use Linux (or at least work inside WSL entirely) in that case though.

---

`BEFORE git clone this repo, i needed to run git config --global core.autocrlf false. this was because in my case, all the .sh files in the Docker image were altered by Git clone process, and the whole setup got messed up and the server wouldn't run`
Are you telling me the Windows version of Docker requires LF and errors on CRLF? (If so, that's really annoying). Or are you launching in WSL but you cloned in standard Windows? (Git by default "autocrlf" uses the line ending of the OS it's used in, so if you use WSL to git clone it should use lf as docker prefers, only uses crlf on winderps.)

Either way, https://github.com/Stability-AI/StableSwarmUI/commit/d0732ed36bc468b0de1013e604fcb9377928cfbb with this commit it should be good now for future users - it forces `.sh` and docker files to always use LF.

----

`i learned about "installing opencv-python-headless python dependency instead of opencv-python. That includes a precompiled binary wheel with no external dependencies (other than numpy), and is intended for headless environments like Docker. This saved almost 700mb in my docker image compared with using the python3-opencv Debian package (with all its dependencies)." - i did this the hard way (editing the file from inside the container), but perhaps this could be worked into a future release. it worked and now manager shows up in the UI`
Oop, yeah, hadn't thought about headless env stuff mattering - https://github.com/Stability-AI/StableSwarmUI/commit/2fdd028813ff1cca06d1a9c6c44dda24ad5d54de fixes that.

---

`i think i did something along the way while wrenching all this, don't know how to undo - there are 2 instances of comfy UI self start backends. every time i delete the 2nd one, when restarting the server it shows up again. i'm sure this is a waste of resources, and probably just a digit in a yaml somewhere, but i can't find it...`

The `launch-docker.sh` by default puts `/Data` into a persistent mount, and that path is where things like backend settings are saved, so it _should_ persist. What can happen though is if swarm is shut down improperly, it might not save settings (the save call is inside the shutdown sequence, so if swarm is forceclosed, it can't save)
I need to make a UI "clean shutdown" button somewhere, but for now the "proper way" to shut down swarm is to hit CTRL+C on the terminal window (ie standard terminal process termination).
(Generally if you hit the shiny red X that works too, but in some environments it doesn't. If you did a docker command to forcekill that also wouldn't work).

----

re `(maybe include a .bat file for Windows Docker users?)` and `WSL Fs up all the mounts, i don't know what to do.` 

I haven't tried windows-docker at all, only tested docker within Linux thus far.  I'll have to find the time at some point to spend setting that up and figuring it all out. (I would welcome a PR though if you figure that all out yourself)

**Comment by mcmonkey4eva** [comment]
There's been several recent PRs from docker users https://github.com/Stability-AI/StableSwarmUI/pull/331 https://github.com/Stability-AI/StableSwarmUI/pull/323 https://github.com/Stability-AI/StableSwarmUI/pull/333 fixing up limitations of swarm docker usage - if you're still having docker users, you might @ nightgrey for help
