### ISSUE TITLE
[Feature Request] Pick multiple values from <random> and <wildcard>

### ISSUE THREAD

**Issue by Jobus0** [Stability-AI/StableSwarmUI#196]
Similarly to [sd-dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts), it should be possible to write syntax that allows `<random:...>` and `<wildcard:...>` to randomly pick more than one value from their respective lists.

Perhaps something like `<random(2):cat,dog,fish>` and `<wildcard(2):animals>` to pick two items at random, but not the same item twice.

Additionally, a range like `<wildcard(1-3):animals>` should be defined to randomly pick one to three values from the list.

For a more concrete example:
Prompt: `<wildcard(2-4):scene_natural>, <wildcard:season>, <wildcard:time>`
Output: `forest, river, heavy clouds, autumn, evening`

(The three `forest, river, heavy clouds` having been picked from `scene_natural`)

This feature would be useful for easily creating more diverse batches.

**Comment by mcmonkey4eva** [comment]
I spent a few days uncertain how to do this best, then decided to go ahead and add multiple variants.

### First:
You can do `<random:1-5>` to pick a random number from 1 to 5.
You can do `<repeat:3,cat>` to get `cat cat cat`
You can combine things and do eg `<repeat:1-3,<random:cat,dog>>` to get eg `cat dog cat`
This is generic and can be mixed however you want to get whatever result you want.
This also allows for eg maybe in the future we go crazy and add math tags or whatever, this would automatically support that.

### Second:
For the more specific case you're actually asking about, I used square brackets `[]` instead of `()` parens but otherwise works mostly how you were thinking.
You can do `<random[2]:cat,dog,fish>` and `<wildcard[2]:animals>` to get any two animals, eg `cat dog`
It uses spaces by default, if you prefer commas you can just add a `,` to the input, ie `<random[2,]:cat,dog,fish>` will get eg `cat, dog`
(The reasoning for this is that the value of commas in a prompt is a common debate, some people think they help, others say they don't... in modern XL they seem even less valuable than they did in SDv1... and even if you prefer them there's plenty of cases where you'd still not want them while otherwise combining random things. So space feels a smarter default in the long run, and this way you can easily choose to have them with no more than a single extra keystroke of the comma key)
You can of course also do eg `1-5` and it does of course also apply to wildcards.

### Also

A notable distinction between option 1 and 2: `<repeat:1-3,<wildcard:animals>>` might give you `cat dog wolf` or `cat cat cat`, but `<wildcard[1-3]:animals>` will avoid repetition, ie `cat cat cat` won't happen.

**Comment by Jobus0** [comment]
Perfect, thank you! Good point about making the commas be optional.
