### ISSUE TITLE
Reuse Parameters doesn't work

### ISSUE THREAD

**Issue by Shadetail** [Stability-AI/StableSwarmUI#199]
Ever since I updated, there seems to be some issues with either writing or reading metadata. For example, when I drag and drop an image onto Stable Swarm UI and I click the "Reuse Parameters" button, I get a popup error message: "No parameters to copy!"
Here is one such example image:
![21-38-57-190-1480558011](https://github.com/Stability-AI/StableSwarmUI/assets/11357447/d194dd09-b59f-4d84-a53d-96a85cf2cd4d)

When I inspect the file, I see that the metadata is there:

> { / "sui_image_params": { / "prompt": "a whimsical and colorful graceful and soft and cute reptilian creature with colorful soaring creative gentle wings, set in an treetops environment. It has large translucent, green wings that resemble those of a stingray or manta ray, with shades of deep blue and emerald green that glow as if reflecting light from the water's surface. Its body is slender, covered in scales that shimmer in hues of green, contributing to its magical appearance. The creature has elongated, whisker-like appendages near its mouth, adding to its fish-like characteristics. Surrounding it are plant-like tendrils and other jungle canopy flora, which are illuminated by a bioluminescent glow, casting a serene light on the scene. The overall atmosphere is one of enchantment and canopy wonder", / "negativeprompt": "(worst quality, low quality:1.4)", / "images": 500, / "seed": 1480558011, / "steps": 50, / "cfgscale": 5.0, / "aspectratio": "1:1", / "width": 1024, / "height": 1024, / "model": "SDXL/realcartoonXL_v5.safetensors", / "loraweights": [ / "0.3" / ], / "clipstopatlayer": -3, / "swarm_version": "0.5.9.0", / "date": "2023-12-05", / "generation_time": "8.01 (prep) and 15.58 (gen) seconds" / } / }

But when I drag and drop a different image I generated with an older version of Stable Swarm then it works, no error, and parameters get applied properly, for example this one:
![16-52-59-13-757224405](https://github.com/Stability-AI/StableSwarmUI/assets/11357447/f0048f3b-a9c6-46a2-9860-30ab9ded378e)

And this is the metadata I see when I inspect that file:

> {"4": {"class_type": "CheckpointLoaderSimple", "inputs": {"ckpt_name": "SDXL\\kohakuXL_alpha7.safetensors"}}, "15": {"class_type": "LoadImage", "inputs": {"image": "init_image_sui_backend_0_1.png"}, "is_changed": ["fa09b9dba251deda0d79437460340fb9646235ce07820950b162d93f3c8a3610"]}, "5": {"class_type": "VAEEncode", "inputs": {"pixels": ["15", 0], "vae": ["4", 2]}}, "6": {"class_type": "CLIPTextEncodeSDXL", "inputs": {"clip": ["4", 1], "text_g": "concept art of alien lava fish teenage humanoid creature mermaid siren, fire and lava melting and flowing, skin made of molten lava, hair made of fire, attractive, hot, cute, perfect body proportions, sirenoid, mermaidoid, molten lava, lava skin, fire, lava, molten flowing lava skin, glowing", "text_l": "concept art of alien lava fish teenage humanoid creature mermaid siren, fire and lava melting and flowing, skin made of molten lava, hair made of fire, attractive, hot, cute, perfect body proportions, sirenoid, mermaidoid, molten lava, lava skin, fire, lava, molten flowing lava skin, glowing", "crop_w": 0, "crop_h": 0, "width": 664, "height": 1192, "target_width": 664, "target_height": 1192}}, "7": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["4", 1], "text": "(worst quality, low quality:1.4), (zombie, sketch, interlocked fingers, comic), human"}}, "10": {"class_type": "KSamplerAdvanced", "inputs": {"model": ["4", 0], "add_noise": "enable", "noise_seed": 757224405, "steps": 20, "cfg": 7.0, "sampler_name": "dpmpp_2m_sde", "scheduler": "karras", "positive": ["6", 0], "negative": ["7", 0], "latent_image": ["5", 0], "start_at_step": 8, "end_at_step": 10000, "return_with_leftover_noise": "disable"}}, "8": {"class_type": "VAEDecode", "inputs": {"samples": ["10", 0], "vae": ["4", 2]}}, "9": {"class_type": "SaveImage", "inputs": {"filename_prefix": "StableSwarmUI_1FB4E4F1_", "images": ["8", 0]}}}

**Comment by mcmonkey4eva** [comment]
The value you copied from the second image is comfy metadata. The actual swarm metadata in old versions was under a different key (Model). In new versions it was moved to Parameters. The `Model` metadata for reference is indeed present on that image with swarm's data.

I'm... very confused what happened / why, with your more recent image -- the metadata is indeed there in the file, and won't load in swarm for me either.
My own images look identical in a local exif metadata checker tool, and mine load fine.
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/dcf48999-5329-40ec-8d8f-7b6996c43a76)

But for whatever reason, the metadata reader lib used in swarm's JS side - https://github.com/MikeKovarik/exifr - doesn't seem to like it? 
This issue is the same holds true on the web exif tool made by the same developer - https://mutiny.cz/exifr/

Everything looks correct, and exifr doesn't give an error, it just ... won't load. I'm so confused what's going on.

Here's my own test image if you can think of any way to test to figure out what's different in metadata.
![0836-a photo of a cat-OfficialStableDiffusionsd_xl_base_10s-902421490](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/5b47f202-3920-4fcb-bd36-8b7069922b08)

**Comment by mcmonkey4eva** [comment]
Update: after testing a bit, I discovered something about it: it's linked to length. If I write a very long prompt, the metadata fails to load in exifr.

The relevant docs for the image library for how it's set say:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/2d2ce0aa-bbc7-4b63-9742-bde8b02f9de4)

So I suspect that potential that `iTXt, tEXt, zTXt` choice varies based on length, and exifr only supports a subset of them.

**Comment by mcmonkey4eva** [comment]
Despite the presence of iTXt references in exifr, it seems unable to load those in my testing when I force it to use that.

The above two commits aggressively force tEXt to always be used, by disabling non-ASCII characters (requires iTXt) and compression (swaps to zTXt), ensuring metadata should always wind up in a format exifr can read.
