### ISSUE TITLE
VAE/noVAE indicator and flow

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#204]
I have a buncha models downloaded. I only just read that one Ive been using for a while, doesnt have a VAE, and recommends use of a particular one.

It would be really nice if, at minimum, something in the model card indicated (bakedVAE/noVAE)

For superduper bonus points, it would be nice if, somewhere in the left-side menu of generations choices, it showed what your current VAE settings are, cross-referenced with what the model has available. So possible values would be(?)

* No VAE selected
* Using model built-in VAE
* Using manually selected VAE (x)
* Using User-preference set VAE(x)

Not sure if that belongs in the "core settings", or "comfyUI" section, or what.

**Comment by mcmonkey4eva** [comment]
So, first: there's no such thing as "no VAE". Every model has a VAE, always. Stable Diffusion doesn't work without one.
Models that "don't have a baked VAE" are models that have some a VAE that the author didn't go out of their way to replace.

For SDv1, this is usually the original compvis era kl-f8. For SDXL, this is one of the two variants of the SDXL VAE (0.9 or 1.0).

For XL it basically entirely doesn't matter (the XL base VAE is perfectly sufficient and nobody's made wonky replacements about it), for SDv1 you generally want ft-mse (the 1.5 tune-up VAE) or NAI (for anime models because NAI cursed their VAE)

"Baked VAE" in SDv1 usually means ft-mse or NAI has been included.
"Baked VAE" on SDXL means absolutely nothing and is just a civitai poster thinking probably the model sounds better if they put that there.

VAE selection is available in the "VAEs" tab at the bottom of the generate tab, you can separately select a preferred default VAE replacement in user settings for SDv1 and SDXL, info about what VAE was used in a generation can be seen in the metadata (unlisted if it used the model's built-in VAE)

* for a user-preference XL VAE replacement you might want this one <https://huggingface.co/madebyollin/sdxl-vae-fp16-fix> which has no "practical result" difference but does run more efficiently (pure fp16) which is nice
