### ISSUE TITLE
SwarmUI + ComfyUI (pre existing backend) = Invalid Operation: No backends match the settings of the request given

### ISSUE THREAD

**Issue by ThisModernDay** [Stability-AI/StableSwarmUI#229]
As the title states, I'm running swarmui with an existing comfyui backend.

I can open the comfyui editor and queue a prompt and it will generate as expected however upon sending the workflow to the swarmui generate tab (using the default comfyui workflow as an example) i'm greeted with the error below
<img width="714" alt="Screenshot 2024-01-29 at 3 39 55 AM" src="https://github.com/Stability-AI/StableSwarmUI/assets/7229462/98d2b5bb-74dc-4188-a953-ca42e8d32e5f">

here are the server settings:
<img width="853" alt="Screenshot 2024-01-29 at 3 42 01 AM" src="https://github.com/Stability-AI/StableSwarmUI/assets/7229462/6ab47edc-ed86-4344-8a8f-cb47e647cf6e">

generate tab:
<img width="1440" alt="Screenshot 2024-01-29 at 3 43 08 AM" src="https://github.com/Stability-AI/StableSwarmUI/assets/7229462/dc7d7305-4ddd-4873-9465-5768665fbc2e">

comfyui workflow tab showing generation working:
<img width="1440" alt="Screenshot 2024-01-29 at 3 45 48 AM" src="https://github.com/Stability-AI/StableSwarmUI/assets/7229462/51777202-ce0e-4d79-ba10-b17b006b26b1">

It is important to note this error occurs whether a save or preview image node is used at the end of the workflow

Also here is the back end page:
<img width="1440" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/7229462/312a1aee-d1f8-486a-97fd-39a65fa52ca9">

**Comment by mcmonkey4eva** [comment]
- I strongly recommend using comfyui_selfstart, not api-by-url
- don't manually specify backendType unless you have a reason to (ie you have multiple different backend types and are comparing results between them)
- Check the `Logs` tab, possibly under `Debug` output, to see what the actual root error is.
- Quite possibly it's just that your models dir in swarm is wrong? ModelRoot should be `F:\ComfyUI\Models`, and SDModelFolder should be `checkpoints`

**Comment by ThisModernDay** [comment]
- I cant get self start to work I've tried several methods (My local instance of comfyui isn't the portable batch it is a full local install that uses conda and a conda virtual env to run comfyui) -- If you have a solution to this I'd love to hear it
- This was just something i changed while troubleshooting I reverted it back after that screen shot
- Logs tab didn't provide any further traceable information just that the error occured
- It was due to my settings being configured wrong changed them to the following below and the issue is resolved
<img width="893" alt="image" src="https://github.com/Stability-AI/StableSwarmUI/assets/7229462/7d640a3d-777c-4246-a3ae-bf9842c0756f">

**Comment by mcmonkey4eva** [comment]
`I cant get self start to work I've tried several methods (My local instance of comfyui isn't the portable batch it is a full local install that uses conda and a conda virtual env to run comfyui) -- If you have a solution to this I'd love to hear it`
Presumably given this, you're fine with writing custom launch scripts to handle the conda stuff and all? Easiest way is just toss together a script that loads the conda env before launching swarm, so that processes launched by swarm are in the conda env ie the comfy_selfstart will be too.

Alternately just position your conda env relative to the comfy install as `../python_embeded` (with typo and all lol) to match the comfy default autoinstall and thus be recognized by swarm.

`Logs tab didn't provide any further traceable information just that the error occurred ( Might recommend a less broad scoped error message and something that pinpoints the issue or throws an error when the model paths aren't set properly)` You got an error output in UI, so there's definitely equal or more information in logs. If it's missing when you went to look, you might just need to replicate the error again to make it appear. (Again use Debug or even Verbose in the log viewer to see more info)

`It was due to my settings being configured wrong changed them to the following below and the issue is resolved` oh so that fixed it? neat
