### ISSUE TITLE
Support A1111 helper extensions?

### ISSUE THREAD

**Issue by jnz86** [Stability-AI/StableSwarmUI#234]
This is likely a no-go. 

But I think it would be of great value to support the accessory not-directly-connected-to-image-generation extensions. The Open Pose 3D modeler, the Civitai Helper / Browser / Installer, a LORA browser with copy and paste activation/training text, etc.

I've found the biggest issue with Comfy is also it's biggest feature, it's an excellent backend. 

An ecosystem already exists for this and it appears to be mostly just giving the extension developer a tab, letting them apply whatever HTML/CSS they like. If this format could be even basically supported and you could use these accessory extensions in Swarm, huge value.

**Comment by mcmonkey4eva** [comment]
` a LORA browser with copy and paste activation/training text, etc.`
Swarm already has a full and detailed model browser for main models, loras, embeds, etc. on the main interface.
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/db21a5c8-600b-4dc8-aff4-bfb579241d45)

`the Civitai Helper / Browser / Installer` I'm hesitant to natively embed an external service, but once you have things downloaded you got a full metadata viewer. I've suggested to civitai they should emit metadata in [standard ModelSpec format](https://github.com/Stability-AI/ModelSpec) in model files but naturally they'd rather have users directly reliant on their servers instead of safe independent data that doesn't earn them ad rev or data collection.

You can of course just manually add the metadata by clicking that ☰ icon then "edit metadata", add keywords under "usage hint" or "trigger phrase", any other info to "description", add an icon too while you're at it.

`The Open Pose 3D modeler` definitely would love to have a pose tool.

` it appears to be mostly just giving the extension developer a tab, letting them apply whatever HTML/CSS they like. If this format could be even basically supported and you could use these accessory extensions in Swarm, huge value.` Swarm has a full extension engine, and in fact many of swarms features come in the form of sample extensions: https://github.com/Stability-AI/StableSwarmUI/tree/master/src/BuiltinExtensions

Anyone can build extensions, just save them into `Swarm/src/Extensions/(YOUR_EXTENSION_NAME)` with code in the same basic setup as the builtin example extensions.

That "Comfy Workflow Editor" tab at the top for example is added by the Comfy extension.

That said I've broadly gone with the idea of just integrating as much natively to the core as possible, so there hasn't been much need for anyone to publish external extensions thus far - when people want something they can generally just get it into Swarm itself rather than needing to build it separately.
