### ISSUE TITLE
Prompt for multiLoRa

### ISSUE THREAD

**Issue by cerarslan** [Stability-AI/StableSwarmUI#24]
When second or another LoRa is used in addition to the LoRa used, the prompt and other settings part does not appear in web-ui, is it possible to add it?

**Comment by mcmonkey4eva** [comment]
Huh?

**Comment by cerarslan** [comment]
> Huh?

When we add the 2nd node LoRa from Comfy Workflow editor, we cannot adjust the 2. LoRa's prompt, weight etc. It is not appearing on first section.  Sorry for my English btw. I hope I could understand the issue. 

You are making an incredible effort. Thank you!

**Comment by mcmonkey4eva** [comment]
As of very recently today, the native UI has its own LoRA options, so you don't need custom workflows for that (but If you're using custom workflows for reasons other than _just_ loras, it's fine to continue using a workflow for it)

The bug where duplicate parameters weren't appearing has been fixed by the commit above
