### ISSUE TITLE
UI bugs encountered

### ISSUE THREAD

**Issue by richardtallent** [Stability-AI/StableSwarmUI#253]
First time user, on Mac. Noticed a few bugs:

- It's not clear for path-based fields whether they should have a trailing "/" or not (turns out no).
- Changing model, etc. paths requires restarting the whole thing. Not mentioned on screen. Refresh buttons on LoRA, etc. doesn't do the truck.
- It's complaining in the log that I don't have ffmpeg.exe. I do have ffmpeg, but it's looking for the wrong executable.

Some UI suggestions for improvement:

- Make font sizes more consistent. I have to scale text on my 30" 4K monitor, but that makes some fonts way too big.
- Many settings use TextArea fields, but are too small to actually wrap correctly when a value is entered. Give them more room by default or switch them to normal inputs.
- Ideally, now we can use File System Access API's showDirectoryPicker to have the user choose a folder! Requires user permission but easier than trying to get and paste an absolute path.
- Lots of "fit and finish" issues with padding, margins, color, text/field/icon alignment, etc. Makes the UI hard to grok.
- Add support in the cards and metadata modal for embeddings and LoRA for the JSON files that are cached by the A1111 CivitAI plugin. These have, for example, the trigger words.
- Move Sampler setting out of the comfyUI heading, it's a critical configuration setting.

The good news:

- Installed with minimum fuss
- Generates images (the most important thing!)
- Being able to use absolute or relative paths allowed me to point to my A1111 folders
- Having ComfyUI around in the background as an option is nice for future flexibility
- The built-in image viewer is nice

**Comment by arcusmaximus** [comment]
@ "Fit and finish": one thing I noticed with the default theme is that dropdowns in the generation parameters have a black background, but textboxes do not, making them look like uneditable text.

Another is the image editor. When you click "Edit Image", the "Use As Init" button stays visible, but the "Init Image" generation parameter (which it normally sends the image to) disappears without telling you why. Then, when I clicked "Use As Init" under the original image on the right and generated a new image, it was actually based on the edited image on the left. It took me some time to realize that the invisible "Init Image" field is indeed ignored (= the "Use As Init" button does nothing) while the image editor is open.

The image editor's layer stack doesn't indicate whether a layer is a Mask layer or an Image layer. Then again, there seems to be no difference between these types in the first place - a Mask layer functions like a regular color layer and does not, in fact, function as an inpainting mask. (I found no documentation explaining how it's supposed to work.)

When you close and reopen the image editor, all your changes are lost.

**Comment by mcmonkey4eva** [comment]
` one thing I noticed with the default theme is that dropdowns in the generation parameters have a black background, but textboxes do not, making them look like uneditable text.`
This is my struggle with UI/UX - I have a strong vision for functionality/accessibility but not aesthetic clarity, so I lean on external commentary/suggestions for that, but it's always dragged back-n-forth. Here's what the UI looked like about a month ago:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/943dcd49-a956-4693-b2cd-24bf4c9e4bda)
The very change you're commenting on here is one made in a PR https://github.com/Stability-AI/StableSwarmUI/pull/233 trying to make the UI more visually clear (dropdowns were given black backgrounds and the rest gray), but for you it made it less clear.

`(= It's not a bug as I initially thought, and the "Use As Init" button effectively does nothing in this state).`
ooh. Yeah that's one to fix, marking that more clearly as disabled or hiding it.

`The image editor's layer stack doesn't indicate whether a layer is a Mask layer or an Image layer.`
Ye I want to clean that up - the image editor is still very underdeveloped and needs a lot more work.

`Then again, there seems to be no difference between these types in the first place - a Mask layer functions like a regular color layer and does not, in fact, function as an inpainting mask. (I found no documentation explaining how it's supposed to work.)`
No a mask layer is a mask layer that acts as a mask. The one unexpected oddity for some is that the "default mask" is all-on currently, ie you have to add a mask layer and draw black to mask things to _not_ draw, and can optionally then add another layer and draw white on it to add things back to keep in.
I want to make controlling the base of the mask easier since it's rather non-obvious atm, and make a clearer yes/no mask selection vs just drawing black n white with the standard brush.

`When you close the image editor, all your changes are lost without warning.`
For clarity on how early-in-dev the image editor specifically was, I only recently added said close button after many complaints that the dev-preview of the image editor was unclosable without refreshing lol

**Comment by arcusmaximus** [comment]
> but for you it made it less clear

It's a matter of consistency, I'd say. I would expect editable fields to use the same colors regardless of their type.

> No a mask layer is a mask layer that acts as a mask

When I wrote that it doesn't, I had just drawn a red blob on a Mask layer, generated an image, and found that the blob made it into the result. Now, however, I can't reproduce that. I was probably drawing on an Image layer without realizing it :)

>  The one unexpected oddity for some is that the "default mask" is all-on currently

Aha. I would've never guessed that - mask layers are transparent by default, which made me assume they work the same as the Inpaint tab in A1111 (transparent means excluded and colored means included). Maybe this could be changed to match the A1111 behavior? After all, the main use case for masking will be to fix small areas, not regenerate everything _except_ for a small area.

> make a clearer yes/no mask selection vs just drawing black n white with the standard brush

That would be nice. Could also make mask layers translucent by default.

Another idea would be to have only one mask layer that can be toggled on/off and is always on top. I'm not sure why you'd want multiple mask layers, or have them obscured by the stuff they're supposed to mask.

**Comment by mcmonkey4eva** [comment]
`maybe the many "?" buttons could be removed to compensate - they could be replaced by hover tooltips` there is an option under user settings to hide the `?` and replace with hover tooltips or hide entirely.

**Comment by Joopz0r** [comment]
Removing the ? makes a world of a difference and I did not know that you could change this.

Need to make editable boxes more clear for the numbers etc

**Comment by mcmonkey4eva** [comment]
`Add support in the cards and metadata modal for embeddings and LoRA for the JSON files that are cached by the A1111 CivitAI plugin. These have, for example, the trigger words.`
A user on discord shared some metadata files from it - apparently there's two different versions with different formats. I've added recognition for both in https://github.com/Stability-AI/StableSwarmUI/commit/44f89604eae4a9ce38f64a0fa0848133a3337742

**Comment by mcmonkey4eva** [comment]
The new Modern Dark theme should cover a lot of the fit-and-finish complaints I imagine.  Or if not... well at least it was designed by an actual UI designer and a Webdev rather than my programmer brain.

The sampler settings are in a proper group now.

The image editor is a lot further along than it used to be. Still not done, but pretty nice to use for basic tasks at least now.

Things aren't perfect yet still, but I'd say at least generally covered what's brought up here enough that any lingering issues should be brought up separately.
