### ISSUE TITLE
A second self start backend with my second GPU goes unutilized in batch generations

### ISSUE THREAD

**Issue by pborah88** [Stability-AI/StableSwarmUI#290]
As per the documentation, I've added a second self start backend and incremented the gpu number. However in both single and batch generations, it only uses gpu 1, gpu 0 goes unutilized. Or vice versa.

6 images in batch
![image](https://github.com/Stability-AI/StableSwarmUI/assets/19488317/095ab4cf-09a8-485c-a55f-f7b132d6c05c)

![image](https://github.com/Stability-AI/StableSwarmUI/assets/19488317/01e58ae3-4d29-46b4-87e5-b2b004e5ee0e)

![image](https://github.com/Stability-AI/StableSwarmUI/assets/19488317/35cc09cc-e359-4a3e-b6e3-a537b327f238)

Torch can see both my GPUs

![image](https://github.com/Stability-AI/StableSwarmUI/assets/19488317/923148e6-ea3f-4f89-8569-a18d1848a768)

**Comment by mcmonkey4eva** [comment]
This... confuses me deeply.
You have OverQueue=1 on each backend, ie a backend may run exactly 2 jobs at once.
You have 2 backends, times two OverQueue = exactly 4 total jobs at once.
And... you have 6 images generating at once.
What?

OH - are you using the internal advanced "Batch" parameter? Yeah no don't use that, use the `Images` parameter at the top. Batch uses a single GPU necessarily, that's it's purpose, and that's why it's hidden under advance. `Images` lets you generate more with automatic queuing.

**Comment by pborah88** [comment]
Thank you!
