### ISSUE TITLE
v2beta api request failed in c#

### ISSUE THREAD

**Issue by maxwell60701** [Stability-AI/StableSwarmUI#339]
I request v2beta api，it is worked both in curl and python ,but wrong in C#
here is my code

using var client = new HttpClient(); 
var request = new HttpRequestMessage(HttpMethod.Post, "https://api.stability.ai/v2beta/stable-image/generate/core");
request.Headers.Add("accept", "image/*");
request.Headers.Add("Authorization", "Bearer my-key");
var content = new MultipartFormDataContent();
content.Add(new StringContent("a cute rabbit"), "prompt");
content.Add(new StringContent("png"), "output_format");
request.Content = content;
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());

Then it reports "Malformed FormData request. Content-Disposition header in FormData part is missing a name"
the above codes are generated by postman

**Comment by mcmonkey4eva** [comment]
How is this relevant to Swarm?

I'll answer anyway cause I know the answer and it's an annoying one, but in general please don't abuse the Swarm issues page for general contact-that-one-monkey-dev-person-who-knows-things

There's a bug in Stability API's cloudflare handler that mishandles unquoted content-disposition headers (despite being example 1 in the RFC https://datatracker.ietf.org/doc/html/rfc6266#section-5 ??? how do mess that up? idek)
C# by default of course properly obeys RFC spec, and so the two things don't get along.

I use these helper functions internally in Stable Artisan to correct for that:
```cs


    /// <summary>Adds a string entry to multipart form data.</summary>
    public static void AddString(this MultipartFormDataContent content, string key, string value)
    {
        content.AddContent(key, null, new StringContent(value));
    }

    /// <summary>Adds a general content entry to multipart form data.</summary>
    public static void AddContent(this MultipartFormDataContent formdata, string key, string filename, HttpContent content)
    {
        content.Headers.ContentDisposition = new("form-data") { Name = $"\"{key}\"", FileName = filename is null ? null : $"\"{filename}\"" };
        if (filename is not null)
        {
            formdata.Add(content, key, filename);
        }
        else
        {
            formdata.Add(content, key);
        }
    }
```
Just dump them in a static util class and then you can eg `content.AddString("prompt", prompt);`

That said I believe I heard they either have now added, or are going to add, support for JSON inputs instead of requiring multipart form, and JSON dodges the issue entirely.

**Comment by maxwell60701** [comment]
I tried to add ContentDisposition ,still not worked,anyway thanks for your help
