### ISSUE TITLE
Custom Node Installation

### ISSUE THREAD

**Issue by cerarslan** [Stability-AI/StableSwarmUI#34]
I managed to install 2 custom nodes with this directory; 'C:\Swarm\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes' I can added them from the add node section, but I couldn't install the one in this link https://civitai.com/models/24690 I don't know if the problem is in this custom node or in SwarmUI, I don't get any error in the terminal. 

By the way, I can also see it when I install it with my separete comfyUI.

**Comment by mcmonkey4eva** [comment]
That one appears to have some extra install steps - looks like you need to copy it all out to the folder, and then run `embedded_install.bat`

Outside of that, I don't see any reason it wouldn't work

**Comment by mcmonkey4eva** [comment]
I tried it, but it doesn't work seemingly just because it has an error when scanning the torch version;
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/53437663-86b2-44bc-a072-e12a5768401d)

I edited `facelib\detection\yolov5face\face_detector.py` line `20` to be:
`IS_HIGH_VERSION = True #tuple(map(int, torch.__version__.split('+')[0].split('.'))) >= (1, 9, 0)`
(ie comment out the value and replace with `True`)

And after that, it works perfectly.
Should probably let the developer of that custom node know

**Comment by cerarslan** [comment]
You are my new hero :)
