### ISSUE TITLE
ComfyUI API By URL requires locally installed models

### ISSUE THREAD

**Issue by Spybyte** [Stability-AI/StableSwarmUI#36]
I installed StableSwarmUI on my Mac without ComfyUI and without models. Just wanted to use a ComfyUI installation on my Linux box. If I want to generate an image I get the error message: Cannot generate, no model selected.

**Comment by mcmonkey4eva** [comment]
Correct, this is a current limitation. The ability to rely on remote models would definitely be a good feature to add though.

**Comment by LargoUsagi** [comment]
All of the models I am leveraging are on a network share that is consistent across all of the machines I am using.  I am not certain if s specific abstraction for locally pulling models is actually needed.

**Comment by mcmonkey4eva** [comment]
On modern versions of Swarm, you can install Swarm on the remote instance, and use Swarm-API-Backend, and it will automatically add the remote model list in. Any models that are available remotely but not locally will have a little marker on them to indicate this fact, but otherwise will work as expected.
