### ISSUE TITLE
Unable to create upscale simple workflow with selectable ESRGAN model input

### ISSUE THREAD

**Issue by Sisimshow** [Stability-AI/StableSwarmUI#382]
I'm trying to make a simple workflow that lets me select an ESRGAN model to upscale an image but from what I can tell there doesn't seem to be a way to select an upscale model using a SwarmInput node. Neither the SwarmInputModelName node nor the SwarmInputDropdown node will connect to the Load Upscale Model node even though they both output COMBO act like they will connect (the model_name input on the Load Upscale Model node highlights when dragging a COMBO output to it but it doesn't connect.)

It may not be a glitch but maybe an oversight. It seems that the SwarmInputModelName node does not have ESRGAN models as a subtype so that may be why it won't connect to the Load Upscale Model node. I tried to use the SwarmInputDropdown node as a workaround by manually listing the models I wanted to use but that doesn't seem to work either. 

Here's just an example of a very simple workflow that I feel should work but doesn't (either with the SwarmInputModelName or the SwarmInputDropdown nodes)
![Screenshot 2024-06-11 032202](https://github.com/Stability-AI/StableSwarmUI/assets/126213271/5d6b5ebb-95b1-4bee-90bc-fec20c8fce76)

You've already done a bunch of work at my request so I understand if you decide to draw the line here. I think though this would be good for a lot of people who would like to replicate, say, the Extras tab from A1111 for just doing a simple ESRGAN upscale. Thank you for everything :)

**Comment by mcmonkey4eva** [comment]
Technically Dropdown is the correct the thing to use, it's just very jank due to comfy litegraph limits with getting `COMBO` inputs to connect together -- you can drag backwards from the `model_name` input, and drop a reroute, then backwards from that to the output the SwarmInput node.

Yes this is extremely cursed, but it's the only way to make litegraph let you do it atm.

The other issue is you have to manually specify the combo values -- I fixed it so you can simply empty the `values` input and it will automatically load the values correct from the node

The other other issue is at some point comfy upstream broke that working with prompt validation... I pushed a commit that... uh... gently bypasses it. Read the commit details at your own risk.

But yeah with the above changes applied, test workflow works as intended
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/e2169e21-ea7b-4cb5-bf13-e28aca1a052f)

**Comment by Sisimshow** [comment]
It works :) you're as awesome as ever! It's janky but with it under a simple workflow I'm not going to care lol thank you again!

**Comment by mcmonkey4eva** [comment]
I was given a much better way to do (empty output type), which now lets you connect directly from the dropdown's output to the input box without the wrangling
