### ISSUE TITLE
"Scoring" get Error

### ISSUE THREAD

**Issue by kadevin** [Stability-AI/StableSwarmUI#69]
Windows 11 3060 12G GPU 16G RAM 
when i use Scoring module get thie error, how do i fix it: 
12:52:11.071 [Error] ScorerExtension error: failed: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
12:52:11.097 [Error] Internal error processing T2I request: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'value'))

**Comment by arathald** [comment]
If anyone else runs across this even after following the scoring install instructions, go into the Scorers directory and activate the venv (per the installation instructions), then run `python -m torch.utils.collect_env` and look for the torch version. If it looks like `[pip3] torch==2.0.1` (without anything immediately after it), you have a version of torch compiled without cuda support. 

You can find specific install instructions for CUDA enabled torch here: https://pytorch.org/get-started/locally/, and you can replace your current version of torch by running (still in venv!) `pip uninstall torch` followed by the command you got from the link (e.g. `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`). Note that the version you pick doesn't have to match any locally installed CUDA toolkit, since torch ships with its own copy of the CUDA libraries.

Once you've done this, run `python -m torch.utils.collect_env` and make sure your torch version ends in '+cu###` (e.g. `[pip3] torch==2.0.1+cu118`), then restart your StableSwarmUI server and try running Scoring again.
