### ISSUE TITLE
Urgent need for localization

### ISSUE THREAD

**Issue by huchang47** [Stability-AI/StableSwarmUI#80]
I am a participant of [a Chinese localization project](https://github.com/hanamizuki-ai/stable-diffusion-webui-localization-zh_Hans) of stable-diffusion-webui. I like StableSwarmUI very much, and hope to do its Chinese localization soon.

**Comment by ahsanba-id** [comment]
I would also like to contribute to Indonesian translation project, but I don't have enough experience in programming and need guidance.

Should we create the translation on our own fork, or can we merge it in a separate file on yours so users can select the option from the main user interface?

**Comment by mcmonkey4eva** [comment]
There isn't tooling to create localizations yet, this issue is a feature request to add that.

It's very much planned, and I have a pretty solid idea of how, it's just a matter of getting to it (between all other priority features).

I pushed it down a little on the priority list, as any localizations made would need to be updated for, uh, well, most of the other priority features, so it's a bit better to push localization after all the things that would need to be localized are more or less done to the point of not being likely to having their messaging change significantly.

**Comment by ahsanba-id** [comment]
Oh, you're right. I'll definitely look forward to another features being added while you keep working on this awesome UI!
