### ISSUE TITLE
Question about the prompt window

### ISSUE THREAD

**Issue by jacksteel13** [Stability-AI/StableSwarmUI#91]
Hello,
First, I wanted to say I love the stableswarmUI app, so thx for all the hard work. 
Also I just updated my stableswarmui to the latest and greatest, and now I see the prompt window is in the middle of my screen, instead of in the left pane above the negative prompt. Just was curious what was the design decision for this?
Thanks again.
Jack

**Comment by mcmonkey4eva** [comment]
https://github.com/Stability-AI/StableSwarmUI/discussions/11#discussioncomment-6848117

Many other UIs work this way (notably "Fooocus" recently got popular by having prompt as the *only* parameter with a similar design), treating the core prompt as the "main focus" of inputs, and the rest of the parameters, as, well, secondary parameters.
In ideal usage of SD, you should be playing with the prompt constantly, and editing other parameters more rarely. (In practice this isn't always true, other parameters are often needed, or at least useful).

This also makes the UI friendlier to less experienced users, as you can literally just close the parameter pane and not worry about those at all, and just type prompts and get images.

In the future I want to expand this a bit more, giving it some of the benefits of the "discord chat bot" style of interface (eg quick-type commands like `/negative yadda yadda` to change your negative, for people who like staying on keyboard instead of swapping to mouse, or the ability to scroll up and quickly see your recent prior generations).

I could make a user-setting to restore the Prompt box on left if people want it.

**Comment by jacksteel13** [comment]
Thanks for explaining, I never try to assume before I get all the info. I definitely see your point, I do like the placement, the one suggestion I would have would be to be able to expand the prompt horizontally, but also, I think having the choice to put it back on the left would be nice as well. 
Thanks
Jack

**Comment by mcmonkey4eva** [comment]
You can expand it as wide as you want horizontally - it's bounded by two draggable bars. You can shrink the parameters and/or batch view to expand prompt.

---

Ref https://github.com/Stability-AI/StableSwarmUI/discussions/11#discussioncomment-6905973 earlier today I added the ability to customize parameter settings via the User tab, so I went ahead now and made sure that mark Prompt as Visible would restore the old visible raw prompt parameter input if you want it.

**Comment by jacksteel13** [comment]
That rocks, thx so much, your right the CTRL+F5 fixed that issue, and love all the new user parameters.  
Jack
