### ISSUE TITLE
Suspend a backend

### ISSUE THREAD

**Issue by AIMusicExperiment** [Stability-AI/StableSwarmUI#93]
Hi, as always thanks to you and your team for your excellent work! As I have three video cards on this machine, I have three backends running. I understand this is helpful when generating multiple images, but for single generation, the additional backends hog GPU resources from other programs, and don't advantage StableSwarm. Is there a way to suspend an unneeded backend without uninstalling it? Also since many integrated motherboard cards have GPUs, is there any advantage to opening a backend without a dedicated GPU for the motherboard?

**Comment by mcmonkey4eva** [comment]
Very good idea, I can see a lot of use cases where you'd want to temporarily disable a backend, or only sometimes enable it (in addition to your own points, I imagine a backend that's on another machine that you don't always care to bother turning on first or something like that).

I've added a lil toggle switch on the left of the backend title bar to quickly turn a backend on or off. It inherently persists in server settings, same as all other settings.

![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/24c09695-e047-4149-9999-668f1bc49f4b)

This also bonus-solves a standing TODO list entry of making an easy way to reload a backend if it dies unexpectedly (now just slap the disable toggler twice! When in doubt, turn it off and back on again, heh)

---

Also unrelated but while I was editing backend UI anyway I added the ability to add custom titles to backends, so you might eg have backends labeled "Local RTX 3090", "My 4090", "Living Room PC", "Server Box", etc. whatever to easily tell what they are if it's not obvious from the config. Can literally just click the title while in backend edit mode and change it.

---

`Also since many integrated motherboard cards have GPUs, is there any advantage to opening a backend without a dedicated GPU for the motherboard?`
I'm not sure what a motherboard integrated GPU is? Do you mean CPU-integrated graphics (Intel Iris/Xe/etc or AMD APUs)? Or laptop (mobile-class) GPUs?

Either way: SD only runs well on GPUs, and usually dedicated GPUs are strongly preferred. Intel integrated graphics is probably flat out a bad idea, AMD APUs _might_ work but will likely be pretty slow. You can technically run SD on CPU directly, but it's _horribly_ slow (takes tens of minutes to generate, vs. a decent GPU generating an image in a few seconds).

Dedicated laptop GPUs (eg an nvidia mobile class) are slower than their desktop equivalents, but still work well. I've tried a laptop mobile RTX 4080 and it runs SD very quickly (at least when plugged in and thus in performance mode).
