### ISSUE TITLE
Layout bars not working

### ISSUE THREAD

**Issue by wibur0620** [Stability-AI/StableSwarmUI#99]
https://github.com/Stability-AI/StableSwarmUI/assets/131615326/bc899020-f053-4481-91b4-57565803c962

**Comment by mcmonkey4eva** [comment]
You. Uh. Can do that. I have no idea what's going on with your clicks? Dragging those bars is the point of those bars, that's why they highlight and give you the lil draggable mouse icon thingy.

Is there something unusual about your browser, or are you accidentally holding down weird keys like control or something?
